//! PTY lifecycle manager — cross-platform via `portable-pty`.
//!
//! Maintains an LRU cache of live PTY processes keyed by `tab_id`.
//! PTYs stay alive across tab switches; switching back is instant (no restart).
//! The cache has a configurable hard cap; the least-recently-used entry is
//! evicted when the cap is reached.

use std::io::{Read, Write};
use std::{collections::HashMap, path::Path};

use anyhow::{Context, Result};
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use parking_lot::Mutex;
use portable_pty::{native_pty_system, Child, CommandBuilder, MasterPty, PtySize};
use tracing::{debug, info, warn};

/// Hard cap on live PTY processes. LRU eviction applies above this limit.
/// Must match `MAX_TABS` in the frontend so the Rust cache never silently
/// evicts (kills) a tab that is still visible in the UI.
const PTY_CACHE_SIZE: usize = 12;
/// Terminal type exposed to child processes. Finder-launched apps inherit `TERM=dumb`.
const PTY_TERM: &str = "xterm-256color";

// ─── Types ────────────────────────────────────────────────────────────────

/// One live PTY session stored in the cache.
pub struct PtySession {
    pub writer: Box<dyn Write + Send>,
    pub child: Box<dyn Child + Send + Sync>,
    pub size: PtySize,
    pub master: Box<dyn MasterPty + Send>,
}

#[derive(Clone, Copy, Debug)]
pub enum PtyProgram<'a> {
    NewSession(&'a Path),
    Resume {
        session_id: &'a str,
        extension: &'a Path,
    },
    Shell,
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
fn omp_command(extension: &Path) -> Result<String> {
    let extension = extension
        .to_str()
        .context("PiArc status extension path is not valid UTF-8")?;
    Ok(format!("omp --extension {}", shell_quote(extension)))
}

fn valid_session_id(session_id: &str) -> bool {
    (6..=128).contains(&session_id.len())
        && session_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

/// OSC 133 (FinalTerm) shell-integration script.
///
/// Hooks into zsh (`precmd`/`preexec`) and bash (`PROMPT_COMMAND`/`DEBUG`
/// trap) to emit escape-sequence markers the terminal can intercept:
/// - `A` = prompt start — shell is idle, awaiting input
/// - `C` = command output start — a command is now running
/// - `D` = command finished — back to idle
fn shell_integration_script() -> &'static str {
    r#"
__piarc_osc133() { printf '\e]133;%s\e\\' "$1"; }
__piarc_preexec() { __piarc_osc133 C; }
__piarc_precmd() { __piarc_osc133 D; __piarc_osc133 A; }
if [ -n "$ZSH_VERSION" ]; then
    precmd_functions+=(__piarc_precmd)
    preexec_functions+=(__piarc_preexec)
    __piarc_osc133 A
elif [ -n "$BASH_VERSION" ]; then
    PROMPT_COMMAND="__piarc_precmd;${PROMPT_COMMAND}"
    trap '__piarc_preexec' DEBUG
    __piarc_osc133 A
fi
"#
}

/// Write the OSC 133 shell-integration wrapper and return the path to a
/// temp directory that should be used as `ZDOTDIR` (for zsh) or the path
/// to a script for `BASH_ENV` (for bash).
///
/// For **zsh**: creates a temp `.zshrc` that (1) unsets `ZDOTDIR`, (2)
/// sources the user's real `~/.zshrc`, then (3) sources the integration
/// script.  Setting `ZDOTDIR` to this temp dir makes the login shell
/// source our wrapper instead of the user's `.zshrc`.
///
/// For **bash**: `BASH_ENV` is sourced at startup, so we just return the
/// integration script path directly.
fn write_integration_wrapper(_shell: &str) -> Result<(std::path::PathBuf, std::path::PathBuf)> {
    let dir = std::env::temp_dir().join("piarc-shell-integration");
    std::fs::create_dir_all(&dir).context("create shell-integration temp dir")?;
    let integ_path = dir.join("piarc_integration.sh");
    std::fs::write(&integ_path, shell_integration_script())
        .with_context(|| format!("write integration to {}", integ_path.display()))?;

    let home = std::env::var("HOME").unwrap_or_default();
    let zshrc = std::path::Path::new(&home).join(".zshrc");
    let zshenv = std::path::Path::new(&home).join(".zshenv");
    let bashrc = std::path::Path::new(&home).join(".bashrc");
    // Wrapper .zshenv: unset ZDOTDIR and source real .zshenv so env setup
    // is not lost.  .zshenv runs before .zshrc for every zsh invocation.
    let zshenv_wrapper = format!(
        "# Auto-generated by PiArc for shell integration.\n\
         unset ZDOTDIR\n\
         if [ -f {zshenv} ]; then source {zshenv}; fi\n",
        zshenv = shell_quote(&zshenv.to_string_lossy()),
    );
    let zdotdir_env = dir.join(".zshenv");
    std::fs::write(&zdotdir_env, &zshenv_wrapper)
        .with_context(|| format!("write wrapper .zshenv to {}", zdotdir_env.display()))?;

    let wrapper = format!(
        "# Auto-generated by PiArc for shell integration.\n\
         unset ZDOTDIR\n\
         if [ -f {zshrc} ]; then source {zshrc}; fi\n\
         if [ -f {integ} ]; then source {integ}; fi\n",
        zshrc = shell_quote(&zshrc.to_string_lossy()),
        integ = shell_quote(&integ_path.to_string_lossy()),
    );
    let zdotdir_rc = dir.join(".zshrc");
    std::fs::write(&zdotdir_rc, &wrapper)
        .with_context(|| format!("write wrapper .zshrc to {}", zdotdir_rc.display()))?;

    // Wrapper for BASH_ENV: source real .bashrc then integration.
    let bash_wrapper = format!(
        "# Auto-generated by PiArc for shell integration.\n\
         if [ -f {bashrc} ]; then source {bashrc}; fi\n\
         if [ -f {integ} ]; then source {integ}; fi\n",
        bashrc = shell_quote(&bashrc.to_string_lossy()),
        integ = shell_quote(&integ_path.to_string_lossy()),
    );
    let bash_env_path = dir.join("piarc_bash_env.sh");
    std::fs::write(&bash_env_path, &bash_wrapper)
        .with_context(|| format!("write bash env to {}", bash_env_path.display()))?;

    Ok((zdotdir_rc, bash_env_path))
}
fn shell_command(program: PtyProgram<'_>, shell: &str) -> Result<String> {
    let shell = shell_quote(shell);
    Ok(match program {
        PtyProgram::NewSession(extension) => {
            format!("{}; exec {shell} -l", omp_command(extension)?)
        }
        PtyProgram::Resume {
            session_id,
            extension,
        } => {
            anyhow::ensure!(
                valid_session_id(session_id),
                "invalid OMP session identifier"
            );
            format!(
                "{} --resume {}; exec {shell} -l",
                omp_command(extension)?,
                shell_quote(session_id)
            )
        }
        PtyProgram::Shell => format!("exec {shell} -l -i"),
    })
}

// ─── Manager ──────────────────────────────────────────────────────────────

/// Thread-safe PTY cache: `tab_id → PtySession`.
pub struct PtyManager {
    sessions: Mutex<HashMap<String, PtySession>>,
    /// Insertion order for LRU eviction (front = oldest).
    lru: Mutex<Vec<String>>,
}

impl PtyManager {
    pub fn new() -> Self {
        Self {
            sessions: Mutex::new(HashMap::new()),
            lru: Mutex::new(Vec::new()),
        }
    }

    // ── Spawn ──────────────────────────────────────────────────────────────

    /// Spawn a new PTY process for `tab_id`, running the selected program in
    /// the requested working directory.
    ///
    /// `on_output(tab_id, base64_chunk)` is called from a background thread
    /// with each output chunk. An **empty chunk** signals process exit.
    pub fn spawn<F>(
        &self,
        tab_id: String,
        program: PtyProgram<'_>,
        cwd: &str,
        size: (u16, u16),
        shell: &str,
        on_output: F,
    ) -> Result<()>
    where
        F: Fn(String, String) + Send + 'static,
    {
        let (cols, rows) = size;
        let cwd = std::fs::canonicalize(cwd).context("resolve PTY working directory")?;
        anyhow::ensure!(cwd.is_dir(), "PTY working directory is not a directory");
        let shell = std::fs::canonicalize(shell).context("resolve login shell")?;
        anyhow::ensure!(shell.is_file(), "login shell is not a regular file");
        let shell = shell.to_string_lossy();

        info!("spawning PTY");

        let pty_system = native_pty_system();
        let size = PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        };
        let pair = pty_system.openpty(size).context("openpty")?;

        let cmd_str = shell_command(program, &shell)?;

        let mut cmd = CommandBuilder::new(shell.as_ref());
        cmd.args(["-l", "-c", &cmd_str]);
        cmd.cwd(cwd);
        cmd.env("TERM", PTY_TERM);
        cmd.env("COLORTERM", "truecolor");
        // Clear NO_COLOR inherited from the parent (Finder-launched apps or
        // terminals with NO_COLOR set). Many CLI tools (codex, etc.) disable
        // all color output when NO_COLOR is present, even if TERM supports it.
        cmd.env_remove("NO_COLOR");

        // Shell integration: set ZDOTDIR (zsh) / BASH_ENV (bash) so the
        // login shell sources our wrapper which sources the user's real
        // config then the OSC 133 integration hooks.
        if matches!(program, PtyProgram::Shell) {
            let (zdotdir, bash_env) =
                write_integration_wrapper(&shell).context("write shell-integration wrapper")?;
            cmd.env("ZDOTDIR", zdotdir.parent().unwrap_or(&zdotdir));
            cmd.env("BASH_ENV", &bash_env);
            cmd.env("ENV", &bash_env);
        }

        let child = pair.slave.spawn_command(cmd).context("spawn PTY child")?;
        let master = pair.master;
        let writer = master.take_writer().context("take PTY writer")?;
        let mut reader = master.try_clone_reader().context("clone PTY reader")?;

        let tid = tab_id.clone();
        std::thread::spawn(move || {
            debug!("PTY reader thread started");
            let mut buf = [0u8; 4096];
            loop {
                match reader.read(&mut buf) {
                    Ok(0) | Err(_) => {
                        info!("PTY process exited");
                        on_output(tid.clone(), String::new()); // empty = exit signal
                        break;
                    }
                    Ok(n) => {
                        on_output(tid.clone(), B64.encode(&buf[..n]));
                    }
                }
            }
        });

        let session = PtySession {
            writer,
            child,
            size,
            master,
        };
        self.evict_if_full();
        self.sessions.lock().insert(tab_id.clone(), session);
        self.touch(&tab_id);
        info!("PTY spawned");
        Ok(())
    }

    // ── I/O ───────────────────────────────────────────────────────────────

    /// Write raw input bytes (keyboard / paste) to the PTY for `tab_id`.
    pub fn write(&self, tab_id: &str, data: &[u8]) -> Result<()> {
        let mut sessions = self.sessions.lock();
        let session = sessions
            .get_mut(tab_id)
            .with_context(|| format!("PTY not found: {tab_id}"))?;
        session.writer.write_all(data).context("write PTY")?;
        drop(sessions);
        self.touch(tab_id);
        Ok(())
    }

    /// Resize the PTY (triggers SIGWINCH on Unix).
    pub fn resize(&self, tab_id: &str, cols: u16, rows: u16) -> Result<()> {
        let mut sessions = self.sessions.lock();
        let session = sessions
            .get_mut(tab_id)
            .with_context(|| format!("PTY not found: {tab_id}"))?;
        let size = PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        };
        session.master.resize(size).context("resize PTY")?;
        session.size = size;
        debug!("PTY resized to {cols}x{rows}");
        Ok(())
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────

    /// Kill a PTY process and remove it from the cache.
    /// Safe to call even if the process has already exited.
    ///
    /// `portable_pty::ChildKiller::kill()` sends SIGHUP, polls `try_wait()`
    /// for 250 ms, then falls back to SIGKILL — but never reaps the child.
    /// `std::process::Child::drop` does not call `waitpid` on Unix, so every
    /// killed child would linger as a zombie until the PiArc process exits.
    /// We call `wait()` after signalling to reap the zombie promptly.
    pub fn kill(&self, tab_id: &str) {
        if let Some(mut session) = self.sessions.lock().remove(tab_id) {
            if session.child.kill().is_err() {
                warn!("PTY termination reported an error");
            } else {
                info!("PTY killed");
            }
            // Reap the zombie.  `kill()` already delivered SIGHUP → SIGKILL,
            // so the child is dead or dying; `wait()` returns within
            // milliseconds.  Without this, each killed PTY lingers as a
            // zombie until the PiArc process exits — after enough kills
            // (tabs opened/closed repeatedly) the system hits `maxproc`
            // and no new processes can be created.
            let _ = session.child.wait();
        }
        self.lru.lock().retain(|id| id != tab_id);
    }

    /// Terminate every child process before the desktop application exits.
    pub fn kill_all(&self) {
        let ids: Vec<String> = self.sessions.lock().keys().cloned().collect();
        for id in ids {
            self.kill(&id);
        }
    }
    /// Returns `true` if a live PTY process exists for `tab_id`.
    pub fn has(&self, tab_id: &str) -> bool {
        self.sessions.lock().contains_key(tab_id)
    }

    // ── LRU helpers ───────────────────────────────────────────────────────

    fn touch(&self, tab_id: &str) {
        let mut lru = self.lru.lock();
        lru.retain(|id| id != tab_id);
        lru.push(tab_id.to_string());
    }

    fn evict_if_full(&self) {
        let oldest = {
            let lru = self.lru.lock();
            if lru.len() >= PTY_CACHE_SIZE {
                lru.first().cloned()
            } else {
                None
            }
        };
        if let Some(id) = oldest {
            warn!("PTY cache full — evicting least recently used process");
            self.kill(&id);
        }
    }
}

impl Default for PtyManager {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for PtyManager {
    fn drop(&mut self) {
        self.kill_all();
    }
}
#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{shell_command, valid_session_id, PtyProgram};

    #[test]
    fn shell_program_opens_login_shell_without_omp() {
        let command = shell_command(PtyProgram::Shell, "/bin/zsh").unwrap();
        assert_eq!(command, "exec '/bin/zsh' -l");
        assert!(!command.contains("omp"));
    }

    #[test]
    fn resume_rejects_shell_syntax_in_session_id() {
        let extension = Path::new("/Applications/PiArc.app/Contents/Resources/piarc-status.js");
        assert!(valid_session_id("019ffe5e-3e7e-7000-a243-ccce1998a378"));
        assert!(shell_command(
            PtyProgram::Resume {
                session_id: "abc; touch /tmp/pwned",
                extension,
            },
            "/bin/zsh"
        )
        .is_err());
        assert!(shell_command(
            PtyProgram::Resume {
                session_id: "$(whoami)",
                extension,
            },
            "/bin/zsh"
        )
        .is_err());
    }

    #[test]
    fn omp_program_loads_status_extension() {
        let extension = Path::new("/tmp/piarc status.js");
        let command = shell_command(PtyProgram::NewSession(extension), "/bin/zsh").unwrap();
        assert_eq!(
            command,
            "omp --extension '/tmp/piarc status.js'; exec '/bin/zsh' -l"
        );
    }

    /// Regression test for the zombie-reaping bug: `kill()` must `wait()` on
    /// the child so no `<defunct>` process remains after the PTY is closed.
    #[test]
    fn kill_reaps_child_no_zombie() {
        use super::{PtyManager, PtyProgram};
        use std::sync::atomic::{AtomicUsize, Ordering};
        use std::sync::Arc;

        let manager = PtyManager::new();
        let counter = Arc::new(AtomicUsize::new(0));
        let c = counter.clone();
        manager
            .spawn(
                "tab-zombie".into(),
                PtyProgram::Shell,
                "/tmp",
                (80, 24),
                "/bin/zsh",
                move |_tid, _data| {
                    c.fetch_add(1, Ordering::SeqCst);
                },
            )
            .expect("spawn");

        // Give the shell a moment to start so we have a real child PID.
        std::thread::sleep(std::time::Duration::from_millis(200));

        // Find the child PID via /proc-free approach: use ps to list children
        // of this test process.  We verify *after* kill that no zombie with
        // that lineage remains.
        let parent_pid = std::process::id() as i32;
        let children_before = child_pids(parent_pid);
        assert!(
            !children_before.is_empty(),
            "expected at least one child process before kill"
        );

        manager.kill("tab-zombie");

        // After kill, give the OS a moment to process the wait().
        std::thread::sleep(std::time::Duration::from_millis(300));

        // No child of this process should be in Z (zombie) state.
        let zombies = zombie_child_pids(parent_pid);
        assert!(
            zombies.is_empty(),
            "zombie processes remain after kill: {zombies:?}"
        );
    }
    /// Regression test for the zombie-reaping bug.  `portable_pty::kill()`
    /// sends SIGHUP → polls `try_wait()` for 250 ms → SIGKILLs, but never
    /// calls `wait()`.  `std::process::Child::drop` skips `waitpid` on Unix,
    /// so the killed child becomes a zombie.  This test verifies that
    /// `PtyManager::kill()` calls `wait()` after signalling, leaving no
    /// zombie behind.
    ///
    /// We use a non-interactive `sleep` that traps SIGHUP to force the
    /// SIGKILL fallback path — the code path where the zombie bug lives.
    #[test]
    fn kill_reaps_sighup_resistant_child_no_zombie() {
        use portable_pty::{native_pty_system, CommandBuilder};

        // Bypass PtyManager::spawn and create a PTY manually so we can
        // spawn a non-interactive SIGHUP-resistant process.  This is the
        // exact scenario that triggers the zombie: the process ignores
        // SIGHUP, so portable_pty's kill() falls back to SIGKILL, and
        // without wait() the child becomes a zombie.
        let pty = native_pty_system();
        let pair = pty
            .openpty(portable_pty::PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("openpty");

        let mut cmd = CommandBuilder::new("/bin/zsh");
        cmd.args(["-c", "trap '' HUP; sleep 30"]);
        cmd.cwd("/tmp");
        cmd.env("TERM", "xterm-256color");

        let mut child = pair.slave.spawn_command(cmd).expect("spawn");
        let _child_pid = child.process_id().expect("pid");

        // Give the shell time to install the trap and enter sleep.
        std::thread::sleep(std::time::Duration::from_millis(500));

        let parent_pid = std::process::id() as i32;

        // Part (a): kill + wait — the fix — should leave no zombie.
        child.kill().expect("kill"); // SIGHUP → SIGKILL
        child.wait().expect("wait"); // <-- the fix: reap the zombie

        std::thread::sleep(std::time::Duration::from_millis(200));

        let zombies = zombie_child_pids(parent_pid);
        assert!(
            zombies.is_empty(),
            "zombie processes remain after kill+wait: {zombies:?}"
        );

        // Part (b): kill WITHOUT wait — old behavior — should leave a zombie.
        // This proves the bug exists and our fix is necessary.
        let pair2 = pty
            .openpty(portable_pty::PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("openpty2");
        let mut cmd2 = CommandBuilder::new("/bin/zsh");
        cmd2.args(["-c", "trap '' HUP; sleep 30"]);
        cmd2.cwd("/tmp");
        cmd2.env("TERM", "xterm-256color");
        let mut child2 = pair2.slave.spawn_command(cmd2).expect("spawn2");
        let _child2_pid = child2.process_id().expect("pid2");

        std::thread::sleep(std::time::Duration::from_millis(500));

        // Intentionally do NOT call wait() — reproduces the old behavior.
        child2.kill().expect("kill2"); // SIGHUP → SIGKILL

        std::thread::sleep(std::time::Duration::from_millis(300));

        let zombies2 = zombie_child_pids(parent_pid);
        assert!(
            !zombies2.is_empty(),
            "expected zombie without wait() (old behavior), got none: {zombies2:?}"
        );

        // Reap the zombie so the test doesn't leak.
        let _ = child2.wait();
    }

    fn child_pids(parent: i32) -> Vec<i32> {
        let out = std::process::Command::new("ps")
            .args(["-o", "pid=,ppid=", "-A"])
            .output()
            .expect("ps");
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .filter_map(|line| {
                let mut parts = line.trim().split_whitespace();
                let pid: i32 = parts.next()?.parse().ok()?;
                let ppid: i32 = parts.next()?.parse().ok()?;
                (ppid == parent).then_some(pid)
            })
            .collect()
    }

    fn zombie_child_pids(parent: i32) -> Vec<i32> {
        // On macOS, `ps` without `-A` omits zombie processes.
        let out = std::process::Command::new("ps")
            .args(["-A", "-o", "pid=,ppid=,stat="])
            .output()
            .expect("ps");
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .filter_map(|line| {
                let mut parts = line.trim().split_whitespace();
                let pid: i32 = parts.next()?.parse().ok()?;
                let ppid: i32 = parts.next()?.parse().ok()?;
                let stat: String = parts.next()?.parse().ok()?;
                (ppid == parent && stat.starts_with('Z')).then_some(pid)
            })
            .collect()
    }
}
